name: linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ main ]
  pull-requests:
    branches: [ main ]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      -uses: actions/checkout@v2
      -name: Starting Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v1
      width:
        node-version: ${{matrix.node-version}}
      -name: install module
      run: npm install
      -name: build production project
      run: npm run build:prod
      -name: linting ts
      run: npm run lint:ts
      -name: linting css
      run: npm run lint:scss
      -name: unut testing
      run: npm run test:unit
